# Generated by Django 5.2.1 on 2025-05-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='producto',
            new_name='product',
        ),
    ]
