# Generated by Django 5.2.1 on 2025-06-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_product_cartitem_service'),
        ('services', '0004_service_rice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
