# Generated by Django 5.2.3 on 2025-06-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_pago_pagoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoitem',
            name='fecha_cita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagoitem',
            name='hora_cita',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
