# Generated by Django 5.2.3 on 2025-06-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_pagoitem_fecha_cita_pagoitem_hora_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='precio_personalizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pagoitem',
            name='precio_personalizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
