# Generated by Django 5.2.3 on 2025-06-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_professional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
