# Generated by Django 5.2.1 on 2025-06-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
