# Generated by Django 5.2.1 on 2025-05-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=30, unique=True)),
                ('description_service', models.CharField(max_length=150)),
                ('price_service', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_service', models.CharField(max_length=20)),
                ('image_service', models.ImageField(blank=True, null=True, upload_to='servicios/')),
            ],
        ),
    ]
